#!/bin/bash

RETVAL=0

# Starts the firewall
start() {
	echo -n "Iptables rule creation: "
	/etc/firewall.sh
	RETVAL=0
}

# Stops the firewall
stop() {
	echo -n "Removing all iptables rules: "
	/etc/flush_iptables.sh
	RETVAL=0
}

case $1 in
	start)
	 start
	 ;;
	stop)
	 stop
	 ;;
	restart)
	 stop
	 start
	 ;;
	status)
	 /sbin/iptables -L
	 RETVAL=0
	 ;;
	*)
	echo "Usage: firewall {start|stop|restart|status}"
	RETVAL=1
esac
